org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

systemProp.org.gradle.s3.endpoint=https://v8j1.or1.idrivee2-63.com

minecraft_version=26.1
loader_version=0.18.5
loom_version=1.15-SNAPSHOT
fabric_kotlin_version=1.13.10+kotlin.2.3.20

mod_version=26.1-0.1.0
maven_group=com.imyvm
archives_base_name=imyvm-world-geo-adventure

fabric_version=0.144.3+26.1
typesafe_version=1.4.3

imyvm_hoki_version=1.1.5
imyvm_world_geo_version=26.1-1.5.0
imyvm_world_geo_community_version=26.1-1.1.0
